// City -> state lookup for the "current city" autocomplete + state auto-fill.
// Not exhaustive (India has thousands of towns) — covers state/UT capitals
// plus the major metros and tier-2 cities candidates are actually based in.
export const INDIAN_CITIES = [
  ['Mumbai', 'Maharashtra'],
  ['Pune', 'Maharashtra'],
  ['Nagpur', 'Maharashtra'],
  ['Nashik', 'Maharashtra'],
  ['Thane', 'Maharashtra'],
  ['Aurangabad', 'Maharashtra'],
  ['Delhi', 'Delhi'],
  ['New Delhi', 'Delhi'],
  ['Bengaluru', 'Karnataka'],
  ['Mysuru', 'Karnataka'],
  ['Hubballi', 'Karnataka'],
  ['Mangaluru', 'Karnataka'],
  ['Hyderabad', 'Telangana'],
  ['Warangal', 'Telangana'],
  ['Chennai', 'Tamil Nadu'],
  ['Coimbatore', 'Tamil Nadu'],
  ['Madurai', 'Tamil Nadu'],
  ['Tiruchirappalli', 'Tamil Nadu'],
  ['Salem', 'Tamil Nadu'],
  ['Kolkata', 'West Bengal'],
  ['Howrah', 'West Bengal'],
  ['Siliguri', 'West Bengal'],
  ['Durgapur', 'West Bengal'],
  ['Ahmedabad', 'Gujarat'],
  ['Surat', 'Gujarat'],
  ['Vadodara', 'Gujarat'],
  ['Rajkot', 'Gujarat'],
  ['Gandhinagar', 'Gujarat'],
  ['Jaipur', 'Rajasthan'],
  ['Jodhpur', 'Rajasthan'],
  ['Udaipur', 'Rajasthan'],
  ['Kota', 'Rajasthan'],
  ['Ajmer', 'Rajasthan'],
  ['Lucknow', 'Uttar Pradesh'],
  ['Kanpur', 'Uttar Pradesh'],
  ['Noida', 'Uttar Pradesh'],
  ['Ghaziabad', 'Uttar Pradesh'],
  ['Agra', 'Uttar Pradesh'],
  ['Varanasi', 'Uttar Pradesh'],
  ['Meerut', 'Uttar Pradesh'],
  ['Prayagraj', 'Uttar Pradesh'],
  ['Bareilly', 'Uttar Pradesh'],
  ['Chandigarh', 'Chandigarh'],
  ['Ludhiana', 'Punjab'],
  ['Amritsar', 'Punjab'],
  ['Jalandhar', 'Punjab'],
  ['Patiala', 'Punjab'],
  ['Mohali', 'Punjab'],
  ['Gurugram', 'Haryana'],
  ['Faridabad', 'Haryana'],
  ['Panipat', 'Haryana'],
  ['Karnal', 'Haryana'],
  ['Bhopal', 'Madhya Pradesh'],
  ['Indore', 'Madhya Pradesh'],
  ['Gwalior', 'Madhya Pradesh'],
  ['Jabalpur', 'Madhya Pradesh'],
  ['Ujjain', 'Madhya Pradesh'],
  ['Patna', 'Bihar'],
  ['Gaya', 'Bihar'],
  ['Bhagalpur', 'Bihar'],
  ['Muzaffarpur', 'Bihar'],
  ['Ranchi', 'Jharkhand'],
  ['Jamshedpur', 'Jharkhand'],
  ['Dhanbad', 'Jharkhand'],
  ['Bhubaneswar', 'Odisha'],
  ['Cuttack', 'Odisha'],
  ['Rourkela', 'Odisha'],
  ['Guwahati', 'Assam'],
  ['Dibrugarh', 'Assam'],
  ['Silchar', 'Assam'],
  ['Thiruvananthapuram', 'Kerala'],
  ['Kochi', 'Kerala'],
  ['Kozhikode', 'Kerala'],
  ['Thrissur', 'Kerala'],
  ['Kollam', 'Kerala'],
  ['Visakhapatnam', 'Andhra Pradesh'],
  ['Vijayawada', 'Andhra Pradesh'],
  ['Guntur', 'Andhra Pradesh'],
  ['Tirupati', 'Andhra Pradesh'],
  ['Dehradun', 'Uttarakhand'],
  ['Haridwar', 'Uttarakhand'],
  ['Roorkee', 'Uttarakhand'],
  ['Raipur', 'Chhattisgarh'],
  ['Bhilai', 'Chhattisgarh'],
  ['Bilaspur', 'Chhattisgarh'],
  ['Shimla', 'Himachal Pradesh'],
  ['Dharamshala', 'Himachal Pradesh'],
  ['Jammu', 'Jammu and Kashmir'],
  ['Srinagar', 'Jammu and Kashmir'],
  ['Panaji', 'Goa'],
  ['Margao', 'Goa'],
  ['Imphal', 'Manipur'],
  ['Shillong', 'Meghalaya'],
  ['Aizawl', 'Mizoram'],
  ['Kohima', 'Nagaland'],
  ['Agartala', 'Tripura'],
  ['Gangtok', 'Sikkim'],
  ['Itanagar', 'Arunachal Pradesh'],
  ['Puducherry', 'Puducherry'],
  ['Remote', 'Remote'],
]

export const CITY_TO_STATE = Object.fromEntries(INDIAN_CITIES.map(([city, state]) => [city.toLowerCase(), state]))

export function stateForCity(city) {
  return CITY_TO_STATE[String(city ?? '').trim().toLowerCase()] ?? ''
}

export function searchCities(query) {
  const q = String(query ?? '').trim().toLowerCase()
  if (!q) return INDIAN_CITIES.map(([city]) => city)
  return INDIAN_CITIES.filter(([city]) => city.toLowerCase().includes(q)).map(([city]) => city)
}
